### PR TITLE
Use 'dyn' since trait objects without an explicit 'dyn' are deprecated

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by apoelstra** [comment]
This doesn't compile with Rust 1.22.

**Comment by Atul9** [comment]
Is there any plan to update the rust version?

**Comment by apoelstra** [comment]
Not really. See https://github.com/rust-bitcoin/rust-bitcoin/issues/338 for some recent discussion.

**Comment by Atul9** [comment]
ok, you can close this PR OR please suggest what change is to be made to fix the build.

**Pull request closed without merging**
